version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: spring_server
    hostname: postgres
    expose:
      - 5432
    ports:
      - 5432:5432
    restart: unless-stopped
    environment:
      POSTGRES_USER: oussama
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: spring_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: spring_server_manager
    environment:
      PGADMIN_DEFAULT_EMAIL: oussama@gmail.Com
      PGADMIN_DEFAULT_PASSWORD: oussama213
    ports:
      - 5050:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres-data:
  pgadmin-data:
