spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_db
    username: oussama
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # Change this to 'update'
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
